// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('devopstest', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('devopstest', async function() {
    await driver.get("http://localhost/")
    await driver.findElement(By.css("input")).click()
    await driver.findElement(By.css("input")).sendKeys("Ali Imran")
    await driver.findElement(By.css("button")).click()
    await driver.findElement(By.css("tr:nth-child(1) > td:nth-child(2)")).click()
    await driver.findElement(By.css(".App")).click()
  })
})
